Projet_django/dashboard/core/urls.py
from django.contrib import admin
from django.urls import path ,include
from django.conf import settings
from django.conf.urls.static import static
from django.views.generic import RedirectView
from core.sitemaps import generate_sitemap


urlpatterns = [
    path('oldadmin/', admin.site.urls),
    path('recommandations/', include('recommandation.urls')),

    path('admin/' , RedirectView.as_view(pattern_name="adminHome"), name='adminRedirect'),
    path('dashboard/' , RedirectView.as_view(pattern_name="adminHome"), name='adminRedirect2'),
    path('', include('adminapp.urls')),
    path('', include('accounts.urls')),
    path('', include('home.urls')),
    path('', include('about.urls')),
    path('', include('contact.urls')),
    path('', include('consommationEau.urls')),
    path('', include('legal.urls')),
    path('', include('marketing.urls')),
    path('', include('planification.urls')),
    path('', include('custompage.urls')),
    path('', include('zones_irrigation.urls')),








    path('capteurs/', include('capteurs.urls')),
    path('sitemap.xml', generate_sitemap, name='generate_sitemap'),
]

handler404 = 'accounts.views.error_404'
handler404 = 'adminapp.views.error_404'
handler404 = 'home.views.error_404'
handler404 = 'contact.views.error_404'
handler404 = 'about.views.error_404'
handler404 = 'settings.views.error_404'
handler404 = 'legal.views.error_404'
handler404 = 'consommationEau.views.error_404'

handler500 = 'adminapp.views.error_500'

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Projet_django/dashboard/home/models.py
from django.db import models
from django.utils.text import slugify
from ckeditor.fields import RichTextField
from accounts.models import User
# Sliders Model
class sliderSection(models.Model):
    image = models.ImageField(upload_to='Home/', blank=True, null=True)
    title = models.CharField(max_length=200, blank=True, null=True)
    subtitle = models.CharField(max_length=200, blank=True, null=True)
    description = models.TextField(blank=True, null=True)
    button1_text = models.CharField(max_length=100, blank=True, null=True)
    button1_url = models.CharField(max_length=500, blank=True, null=True)
    button2_text = models.CharField(max_length=100, blank=True, null=True)
    button2_url = models.CharField(max_length=500, blank=True, null=True)

    def __str__(self):
        return self.title

    class Meta:
        verbose_name_plural = "1. Slider Section"

# Services Model
class serviceSection(models.Model):
    name = models.CharField(max_length=200, blank=True, null=True)
    slug = models.SlugField(blank=True, null=True)
    short_description = models.CharField(max_length=500, blank=True, null=True)
    fontawesome_icon_class = models.CharField(max_length=100, blank=True, null=True)
    detail_page_image = models.ImageField(upload_to='Services/', blank=True, null=True)
    detail_page_description = RichTextField(blank=True, null=True)
    show_call_now_widget = models.BooleanField(default=True)

    def save(self, *args, **kwargs):
        self.slug = slugify(self.name)
        super().save(*args, **kwargs)

    def __str__(self):
        return self.name
    
    class Meta:
        verbose_name_plural = "2. Service Section"
        
# About Section Model
class aboutSection(models.Model):
    subtitle = models.CharField(max_length=200, blank=True, null=True)
    title = models.CharField(max_length=200, blank=True, null=True)
    short_description = models.CharField(max_length=200, blank=True, null=True)
    long_description = models.TextField(blank=True, null=True)
    ranking_number = models.IntegerField(blank=True, null=True)
    tag_line = models.CharField(max_length=200, blank=True, null=True)
    experience = models.CharField(max_length=200, blank=True, null=True)
    
    image = models.ImageField(upload_to='AboutSection/', blank=True, null=True)
    video_thumbnail = models.ImageField(upload_to='AboutSection/', blank=True, null=True)
    video_url = models.CharField(max_length=500, blank=True, null=True)

    def __str__(self):
        return self.title
    
    class Meta:
        verbose_name_plural = "3. About Section"

# Funfacts Section Model
class funFactSection(models.Model):
    fontawesome_icon_class = models.CharField(max_length=200, blank=True, null=True)
    count = models.IntegerField(blank=True, null=True)
    count_after = models.CharField(max_length=20, blank=True, null=True)
    title = models.CharField(max_length=200, blank=True, null=True)

    def __str__(self):
        return self.title
    
    class Meta:
        verbose_name_plural = "4. Fun Fact Section"

# Project and Project category Section Model
class projectCategory(models.Model):
    name = models.CharField(max_length=200, blank=True, null=True)
    slug = models.SlugField(blank=True, null=True)

    def save(self, *args, **kwargs):
        self.slug = slugify(self.name)
        super().save(*args, **kwargs)

    def __str__(self):
        return self.name
    
class projectSection(models.Model):
    image = models.ImageField(upload_to='Projects/', blank=True, null=True)
    category = models.ForeignKey(projectCategory, blank=True, null=True, on_delete=models.SET_NULL)
    title = models.CharField(max_length=200, blank=True, null=True)
    slug = models.SlugField(blank=True, null=True)
    description = RichTextField(blank=True, null=True)
    client = models.CharField(max_length=200, blank=True, null=True)
    company = models.CharField(max_length=200, blank=True, null=True)
    duration = models.CharField(max_length=100, blank=True, null=True)

    def save(self, *args, **kwargs):
        self.slug = slugify(self.title)
        super().save(*args, **kwargs)
        
    def getProjectImage(self):
        if self.image:
            return self.image.url
        else:
            return 'https://t4.ftcdn.net/jpg/04/73/25/49/360_F_473254957_bxG9yf4ly7OBO5I0O5KABlN930GwaMQz.jpg'

    def __str__(self):
        return self.title
    
    class Meta:
        verbose_name_plural = "5.Project Section"

# Client Section Model
class clientSection(models.Model):
    client_name = models.CharField(max_length=100, blank=True, null=True)
    image = models.ImageField(upload_to='Clients/', blank=True, null=True)

    def __str__(self):
        return self.client_name

    class Meta:
        verbose_name_plural = "6.Client Section"

# Testimonials Model
class testimonialsSection(models.Model):
    name = models.CharField(max_length=200, blank=True, null=True)
    position = models.CharField(max_length=100, blank=True, null=True)
    description = models.TextField(blank=True, null=True)
    image = models.ImageField(upload_to='Testimonials/', blank=True, null=True)
    star = models.IntegerField(blank=True, null=True)

    def __str__(self):
        return self.name
    
    class Meta:
        verbose_name_plural = "7.Testimonial Section"

# Home Page SEO Model
class homePageSEO(models.Model):
    meta_title = models.CharField(max_length=500, blank=True, null=True)
    meta_description = models.CharField(max_length=1000, blank=True, null=True)

    def __str__(self):
        return self.meta_title

class Irrigation(models.Model):
    TYPE_IRRIGATION_CHOICES = [
        ('Goutte à goutte', 'Goutte à goutte'),
        ('Aspersion', 'Aspersion'),
        ('Surface', 'Surface'),
        ('Sous-irrigation', 'Sous-irrigation'),
    ]

    user = models.ForeignKey(User, on_delete=models.CASCADE)
    nom = models.CharField(max_length=100)
    type_irrigation = models.CharField(max_length=50, choices=TYPE_IRRIGATION_CHOICES)
    description = models.TextField(blank=True, null=True)

    def __str__(self):
        return f'Irrigation: {self.nom} ({self.type_irrigation})'
    def get_consommations(self):
        """Return all consommation associated with this irrigation."""
        return self.consommations.all()
    class Meta:
        verbose_name_plural = "8.Irrigation Section"

class ConsommationEau(models.Model):
    PHASES_CULTURE = [
        ('Germination', 'Germination'),
        ('Croissance', 'Croissance'),
        ('Floraison', 'Floraison'),
        ('Maturation', 'Maturation'),
    ]

    user = models.ForeignKey(User, on_delete=models.CASCADE)  # Relation avec l'utilisateur
    irrigation = models.ForeignKey(Irrigation, on_delete=models.CASCADE, related_name='consommations',null=True, blank=True)
    id = models.AutoField(primary_key=True)
    date_heure = models.DateTimeField()
    quantite_consommee = models.FloatField()
    temperature = models.FloatField()  # Température en °C
    humidite = models.FloatField()      # Humidité en %
    precipitations = models.FloatField()  # Précipitations en mm
    type_culture = models.CharField(max_length=100)  # Type de culture
    phase_culture = models.CharField(max_length=50, choices=PHASES_CULTURE)  # Phase de croissance de la culture

    def __str__(self):
        return f'{self.date_heure} - {self.quantité_consommée} L par {self.user.username}'
    class Meta:
        verbose_name_plural = "8.water consumption Section"

Projet_django/dashboard/templates/dashboard/main/elements/pricing/create.html
{% extends 'dashboard/base.html' %}
{% load static %}
{% block title %}{{ title }} - {{ seo_settings.meta_title }}{% endblock title %}
{% block content %}
<style>
    label.switch {
        margin-top: -35px;
    }
  </style>
<div class="page-body">
   <div class="container-fluid">
      <div class="page-title">
         <div class="row">
            <div class="col-6">
               <h3>Create Pricing</h3>
            </div>
            <div class="col-6">
               <ol class="breadcrumb">
                  <li class="breadcrumb-item">
                     <a href="{% url 'adminHome' %}">
                        <svg class="stroke-icon">
                           <use href="{% static 'admin/assets/svg/icon-sprite.svg' %}#stroke-home"></use>
                        </svg>
                     </a>
                  </li>
                  <li class="breadcrumb-item">Elements</li>
                  <li class="breadcrumb-item active">Create Pricing</li>
               </ol>
            </div>
         </div>
      </div>
   </div>
   <!-- Container-fluid starts-->
   <div class="container-fluid">
      <div class="row project-cards">
         <div class="col-md-12 project-list">
         </div>
         <div class="container">
            <form method="POST" enctype="multipart/form-data">
               {% csrf_token %}
               {{form.media}}   
               {% if form.errors %}
               <div class="alert alert-danger">
                  <strong>Error:</strong>
                  <ul>
                     {% for field, errors in form.errors.items %}
                     {% for error in errors %}
                     <li>{{ field }}: {{ error }}</li>
                     {% endfor %}
                     {% endfor %}
                  </ul>
               </div>
               {% endif %}                   
               <div class="row mb-3">
                  <div class="col-md-4">
                     <div class="card">
                        <div class="card-body">
                           <label for="{{ form.name.id_for_label }}" class="form-label">Title</label>
                           {{ form.title }}
                        </div>
                     </div>
                  </div>
                  <div class="col-md-4">
                     <div class="card">
                        <div class="card-body">
                           <label for="{{ form.position.id_for_label }}" class="form-label">Subtitle</label>
                           {{ form.subtitle }}
                        </div>
                     </div>
                  </div>
                  <div class="col-md-4">
                    <div class="card">
                       <div class="card-body">
                          <label for="{{ form.star.id_for_label }}" class="form-label">Price</label>
                          <div class="input-group">
                            <span class="input-group-text">{{ settings.currency_symbol }}</span>
                            {{form.price}}
                        </div>
                       </div>
                    </div>
                 </div>
               </div>
               <div class="row mb-3">
                <div class="col-md-6">
                   <div class="card">
                      <div class="card-body">
                         <label for="{{ form.button_text.id_for_label }}" class="form-label">Button Text</label>
                         {{ form.button_text }}
                      </div>
                   </div>
                </div>
                <div class="col-md-6">
                   <div class="card">
                      <div class="card-body">
                         <label for="{{ form.button_url.id_for_label }}" class="form-label">Button Url</label>
                         {{ form.button_url }}
                      </div>
                   </div>
                </div>
             </div>
               <div class="row mb-3">
                <div class="col-md-6">
                   <div class="card">
                      <div class="card-body">
                         <label for="{{ form.description.id_for_label }}" class="col-form-label ">Is Featured?</label>
                        <div class="media-body text-end icon-state">
                          <label class="switch">
                            {{ form.is_featured }}<span class="switch-state"></span>
                          </label>
                        </div>
                      </div>
                   </div>
                </div>
                <div class="col-md-6">
                    <div class="card">
                       <div class="card-body">
                          <label for="{{ form.description.id_for_label }}" class="form-label">Featured Badge Text</label>
                          {{ form.featured_text }}
                       </div>
                    </div>
                 </div>
             </div>
               <div class="row mb-1">
                  <div class="col-md-12">
                     <div class="card">
                        <div class="card-body">
                           <label for="{{ form.description.id_for_label }}" class="form-label">Description</label>
                           <br>
                           <div class="form-control ckf" style="">{{ form.description }}</div>
                        </div>
                     </div>
                  </div>
               </div>
               <button class="btn btn-primary mb-3" type="submit">Save</button>
            </form>
         </div>
      </div>
   </div>
</div>
<!-- Container-fluid Ends-->
<script>
    document.addEventListener('DOMContentLoaded', function() {
        const progressInput = document.querySelector('#id_star');
        
        progressInput.addEventListener('input', function() {
            const value = parseInt(progressInput.value);
            if (isNaN(value)) {
                progressInput.value = '';
            } else {
                progressInput.value = Math.min(value, 5);
            }
        });
    });
</script>
{% endblock %}

Projet_django/dashboard/templates/dashboard/main/elements/pricing/edit.html
{% extends 'dashboard/base.html' %}
{% load static %}
{% block title %}{{ title }} - {{ seo_settings.meta_title }}{% endblock title %}
{% block content %}
<style>
    label.switch {
        margin-top: -35px;
    }
  </style>
<div class="page-body">
   <div class="container-fluid">
      <div class="page-title">
         <div class="row">
            <div class="col-6">
               <h3>Edit Pricing</h3>
            </div>
            <div class="col-6">
               <ol class="breadcrumb">
                  <li class="breadcrumb-item">
                     <a href="{% url 'adminHome' %}">
                        <svg class="stroke-icon">
                           <use href="{% static 'admin/assets/svg/icon-sprite.svg' %}#stroke-home"></use>
                        </svg>
                     </a>
                  </li>
                  <li class="breadcrumb-item">Elements</li>
                  <li class="breadcrumb-item active">Edit Pricing</li>
               </ol>
            </div>
         </div>
      </div>
   </div>
   <!-- Container-fluid starts-->
   <div class="container-fluid">
      <div class="row project-cards">
         <div class="col-md-12 project-list">
         </div>
         <div class="container">
            <form method="POST" enctype="multipart/form-data">
               {% csrf_token %}
               {{form.media}}   
               {% if form.errors %}
               <div class="alert alert-danger">
                  <strong>Error:</strong>
                  <ul>
                     {% for field, errors in form.errors.items %}
                     {% for error in errors %}
                     <li>{{ field }}: {{ error }}</li>
                     {% endfor %}
                     {% endfor %}
                  </ul>
               </div>
               {% endif %}                   
               <div class="row mb-3">
                  <div class="col-md-4">
                     <div class="card">
                        <div class="card-body">
                           <label for="{{ form.name.id_for_label }}" class="form-label">Title</label>
                           {{ form.title }}
                        </div>
                     </div>
                  </div>
                  <div class="col-md-4">
                     <div class="card">
                        <div class="card-body">
                           <label for="{{ form.position.id_for_label }}" class="form-label">Subtitle</label>
                           {{ form.subtitle }}
                        </div>
                     </div>
                  </div>
                  <div class="col-md-4">
                    <div class="card">
                       <div class="card-body">
                          <label for="{{ form.star.id_for_label }}" class="form-label">Price</label>
                          <div class="input-group">
                            <span class="input-group-text">{{ settings.currency_symbol }}</span>
                            {{form.price}}
                        </div>
                       </div>
                    </div>
                 </div>
               </div>
               <div class="row mb-3">
                <div class="col-md-6">
                   <div class="card">
                      <div class="card-body">
                         <label for="{{ form.button_text.id_for_label }}" class="form-label">Button Text</label>
                         {{ form.button_text }}
                      </div>
                   </div>
                </div>
                <div class="col-md-6">
                   <div class="card">
                      <div class="card-body">
                         <label for="{{ form.button_url.id_for_label }}" class="form-label">Button Url</label>
                         {{ form.button_url }}
                      </div>
                   </div>
                </div>
             </div>
               <div class="row mb-3">
                <div class="col-md-6">
                   <div class="card">
                      <div class="card-body">
                         <label for="{{ form.description.id_for_label }}" class="col-form-label ">Is Featured?</label>
                        <div class="media-body text-end icon-state">
                          <label class="switch">
                            {{ form.is_featured }}<span class="switch-state"></span>
                          </label>
                        </div>
                      </div>
                   </div>
                </div>
                <div class="col-md-6">
                    <div class="card">
                       <div class="card-body">
                          <label for="{{ form.description.id_for_label }}" class="form-label">Featured Badge Text</label>
                          {{ form.featured_text }}
                       </div>
                    </div>
                 </div>
             </div>
               <div class="row mb-1">
                  <div class="col-md-12">
                     <div class="card">
                        <div class="card-body">
                           <label for="{{ form.description.id_for_label }}" class="form-label">Description</label>
                           <br>
                           <div class="form-control ckf" style="">{{ form.description }}</div>
                        </div>
                     </div>
                  </div>
               </div>
               <button class="btn btn-primary mb-3" type="submit">Save</button>
            </form>
         </div>
      </div>
   </div>
</div>
<!-- Container-fluid Ends-->
<script>
    document.addEventListener('DOMContentLoaded', function() {
        const progressInput = document.querySelector('#id_star');
        
        progressInput.addEventListener('input', function() {
            const value = parseInt(progressInput.value);
            if (isNaN(value)) {
                progressInput.value = '';
            } else {
                progressInput.value = Math.min(value, 5);
            }
        });
    });
</script>
{% endblock %}

Projet_django/dashboard/templates/dashboard/main/elements/pricing/pricing.html
{% extends 'dashboard/base.html' %}
{% load static %}
{% block title %}{{ title }} - {{ seo_settings.meta_title }}{% endblock title %}
{% block content %}
<style>
  .icon {
      display: inline-block;
      width: 20px;
      height: 20px;
      border-radius: 50%;
      text-align: center;
      line-height: 20px;
      font-weight: bold;
      font-size: 14px;
    }
    
    .green {
      background-color: #54BA4A;
      color: white;
    }
    
    .red {
      background-color: #FC4438;
      color: white;
    }
    
</style>
<div class="page-body">
    <div class="container-fluid">
      <div class="page-title">
        <div class="row">
          <div class="col-6">
            <h3>Pricing</h3>
          </div>
          <div class="col-6">
            <ol class="breadcrumb">
              <li class="breadcrumb-item"><a href="{% url 'adminHome' %}">                                       
                  <svg class="stroke-icon">
                    <use href="{% static 'admin/assets/svg/icon-sprite.svg' %}#stroke-home"></use>
                  </svg></a></li>
              <li class="breadcrumb-item">Elements</li>
              <li class="breadcrumb-item active">Pricing</li>
            </ol>
          </div>
        </div>
      </div>
    </div>
    <!-- Container-fluid starts-->
    <div class="container-fluid">
      {% if messages %}
        {% for message in messages %}
            <div class="alert alert-{{ message.tags }} alert-dismissible fade show" role="alert">
                {{ message }}
                <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
            </div>
        {% endfor %}
      {% endif %} 
        <div class="col-md-12 project-list">
            <div class="card">
              <div class="row">
                <div class="col-md-6 p-0 d-flex">
                  <ul class="nav nav-tabs border-tab" id="top-tab" role="tablist">
                    <li class="nav-item"><a class="nav-link active" id="top-home-tab" data-bs-toggle="tab" href="#top-home" role="tab" aria-controls="top-home" aria-selected="true"><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-target"><circle cx="12" cy="12" r="10"></circle><circle cx="12" cy="12" r="6"></circle><circle cx="12" cy="12" r="2"></circle></svg>All Pricings</a></li>
                   </ul>
                </div>
                <div class="col-md-6 p-0">                    
                  <div class="form-group mb-0 me-0"></div><a class="btn btn-primary" href="{% url 'adminPricingElementCreate' %}"> <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-plus-square"><rect x="3" y="3" width="18" height="18" rx="2" ry="2"></rect><line x1="12" y1="8" x2="12" y2="16"></line><line x1="8" y1="12" x2="16" y2="12"></line></svg>Create New Pricing</a>
                </div>
              </div>
            </div>
          </div>
      <div class="row">
        <!-- Zero Configuration  Starts-->
        <div class="col-sm-12">
          <div class="card">
            <div class="card-body">
              <div class="table-responsive">
                <table class="display" id="basic-1">
                  <thead>
                    <tr>
                      <th>#</th>
                      <th>Title</th>
                      <th>Sub Title</th>
                      <th>Button</th>
                      <th>Is Featured</th>
                      <th>Action</th>
                    </tr>
                  </thead>
                  <tbody>
                    {% for pricing in pricings %}
                    <tr>
                      <td>{{ forloop.counter }}</td>
                      <td><a href="{% url 'adminPricingElementEdit' pricing.id %}">{{ pricing.title }}</a></td>
                      <td>{{ pricing.subtitle }}</td>
                      <td>{{ pricing.button_text }}</td>
                      <td>
                        {% if pricing.is_featured %}
                          <span class="icon green">&#10003;</span>
                        {% else %}
                          <span class="icon red">&#10005;</span>
                        {% endif %}
                      </td>
                      <td> 
                        <ul class="action"> 
                          <li class="edit"> <a href="{% url 'adminPricingElementEdit' pricing.id %}"><i class="icon-pencil-alt"></i></a></li>
                          <li class="delete"><a href="#" data-slug="{{ pricing.id }}"><i class="icon-trash"></i></a></li>
                          <script>
                            document.addEventListener('DOMContentLoaded', (event) => {
                                var deleteButtons = document.querySelectorAll('.icon-trash');
                          
                                deleteButtons.forEach(function(button) {
                                    button.addEventListener('click', function (event) {
                                        event.preventDefault();
                          
                                        var url = "{% url 'adminPricingElementDelete' pricing.id %}";
                          
                                        Swal.fire({
                                            title: 'Are you sure?',
                                            text: "You won't be able to revert this!",
                                            icon: 'warning',
                                            showCancelButton: true,
                                            confirmButtonColor: '#3085d6',
                                            cancelButtonColor: '#d33',
                                            confirmButtonText: 'Yes, delete it!'
                                        }).then((result) => {
                                            if (result.isConfirmed) {
                                                window.location.href = url;
                                            }
                                        })
                                    });
                                });
                            });
                          </script>
                        </ul>
                      </td>
                    </tr>
                    {% endfor %}
                  </tbody>
                </table>
              </div>
            </div>
          </div>
        </div>
        <!-- Zero Configuration  Ends-->
    </div>
</div>
</div>
{% endblock %}